<?xml version="1.0" encoding="utf-8"?><Database Name="LucaToysData" Class="LucaToysLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\LucaToysData.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="LucaToys.Properties.Settings" SettingsPropertyName="LucaToysDataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="usercode" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="family" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="instagram" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="postalcode" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="gmail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>